<div class="page-width shopify-policy__container">
    <div class="shopify-policy__title">
        <h1>Política de privacidad</h1>
    </div>
    <div class="shopify-policy__body">
        <div class="rte">
            <p>Estas políticas de privacidad (las “Políticas de Privacidad”) entrarán en vigor desde su aceptación para los nuevos usuarios y están vigentes desde 21 de junio de 2021.</p>
            <p>La privacidad de la información de los usuarios es muy importante para ÉLITE JOYERÍA. Es por esa razón que se toman las precauciones y recaudos para resguardar su información, utilizando los mecanismos de seguridad informática de protección de la información más completos y eficaces. Como parte normal de nuestra actividad recogemos y, en algunos casos, revelamos información sobre nuestros usuarios y visitantes de nuestro sitio Web. Estas Políticas de Privacidad describen la información que ÉLITE JOYERÍA recoge sobre sus usuarios y visitantes y lo que puede hacerse con dicha información. Esta política es muy detallada porque es importante que todos los usuarios y visitantes de nuestro sitio Web conozcan las prácticas de ÉLITE JOYERÍA de la forma más precisa posible. Al inscribirse y/o navegar el sitio Web de ÉLITE JOYERÍA, el usuario y/o el visitante presta su consentimiento inequívoco para que se utilice su información personal de acuerdo a las políticas que se describen a continuación.</p>
            <p>Este documento es parte integrante de los Términos y Condiciones Generales de ÉLITE JOYERÍA. Mediante la aceptación de los Términos y Condiciones Generales en el momento de la inscripción el usuario acepta las políticas aquí contenidas.<br></p>
            <p><strong>Derechos de acceso, retiro y rectificación de la información personal</strong></p>
            <p>Los usuarios tienen reconocidos y podrán ejercitar los derechos de conocer, acceder, retirar y actualizar su Información Personal, incluyendo su dirección de e-mail, así como a oponerse al tratamiento de la misma y a ser informado de las cesiones llevadas a cabo, todo ello de conformidad a lo dispuesto en la normativa aplicable. Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de la Información Personal facilitada, y se comprometen a mantenerla debidamente actualizada.</p>
            <p>Una vez inscrito en ÉLITE JOYERÍA, el usuario podrá revisar y cambiar la información que nos ha enviado durante el proceso de inscripción incluyendo:</p>
            <ul>
                <li>el Seudónimo y dirección de correo electrónico. Sin perjuicio de los cambios que realice, ÉLITE JOYERÍA conservará la Información Personal anterior por motivos de seguridad y control del fraude.</li>
                <li>la información de la inscripción como: compañía, domicilio, ciudad, región, código postal, número principal de teléfono, número secundario de teléfono, número de fax, correo electrónico, etc.</li>
                <li>la clave.</li>
            </ul>
            <p>En determinados casos, mantendremos en nuestros archivos Información Personal que nos hayas pedido que retiremos, y ello con la finalidad de resolver disputas o reclamaciones, detectar problemas o incidencias y solucionarlos, y dar cumplimiento a lo dispuesto en los Términos y Condiciones Generales por un período de tiempo determinado por la ley o determinado por la finalidad que se persiga. En cualquier caso, la Información Personal de un usuario no será inmediatamente retirada de nuestros archivos por motivos legales y técnicos, incluyendo sistemas de soportes de seguridad. Por tanto, no se debe esperar que toda la Información Personal sea definitivamente borrada de nuestras bases de datos lo cual es entendido y aceptado por los usuarios al aceptar los Términos y Condiciones y las Políticas de Privacidad.</p>
            <p>Los usuarios deben actualizar su Información Personal periódicamente conforme vaya cambiando para que los otros usuarios puedan ubicarlos cuando realicen una operación. Para hacer cualquier modificación en la información que, suministrada en el momento de la Inscripción, se debe ingresar en la sección Mi cuenta.</p>
            <p>ÉLITE JOYERÍA podrá modificar en cualquier momento los términos y condiciones de estas Políticas de Privacidad y confidencialidad y/o las prácticas de envío de e-mails. Si decidimos introducir algún cambio material a nuestras Políticas de Privacidad, te notificaremos publicando una versión actualizada de las Políticas en esta sección o mediante el envío de un e-mail o informándolo en la página principal u otras secciones del sitio para mantenerte actualizado de los cambios realizados.</p>
            <p>Si hacemos cambios materiales en la forma que tu Información personal es administrada, te notificaremos por e-mail para que puedas tomar una decisión informada respecto si aceptas o no que tu Información Personal sea utilizada de esa forma. Si no aceptas esos términos, en ese caso quedará disuelto el vínculo contractual y tu Información Personal no será usada de otra forma que la que fue informada al momento de recabarse.</p>
            <p>Para mayor información sobre la confidencialidad de tu Información Personal, contáctanos por correo electrónico o postal.</p>
            <p>Por correo ordinario a: elitejoyeria18k@gmail.com</p>
            <p>Dirección postal: Calle 52 # 47-28, Edificio La Ceiba, local 425, Medellín, Antioquia – Colombia</p>
            <p><strong>La información que recabamos</strong></p>
            <p>Lo primero que se debe hacer para disfrutar de los servicios de ÉLITE JOYERÍA es inscribirse, suministrando ciertos datos personales (“Información Personal”) completos y exactos. Podremos solicitar, recabar y almacenar la siguiente Información Personal: apodo o seudónimo para operar en el sitio de ÉLITE JOYERÍA, nombre, número de documento o identificación válida, información física de contacto (como número de teléfono domicilio, dirección de e-mail, etc.). ÉLITE JOYERÍA podrá confirmar los datos personales suministrados acudiendo a entidades públicas, compañías especializadas o centrales de riesgo, para lo cual nos autorizas expresamente. La información que ÉLITE JOYERÍA obtenga de estas entidades será tratada en forma confidencial.</p>
            <p>El Usuario que se registre en ÉLITE JOYERÍA a través de su cuenta personal en una red social (“Cuenta Personal”), o de cualquier modo acceda a ÉLITE JOYERÍA a través de su Cuenta Personal, consiente expresamente que ÉLITE JOYERÍA:</p>
            <ul>
                <li>Tenga acceso, en cualquier momento, a la totalidad de la información contenida en su Cuenta Personal, incluyendo en particular, pero sin limitación, a su Información Personal, información sobre sus intereses, gustos, contactos y cualquier otro contenido alojado en su Cuenta Personal;</li>
                <li>incluya en dicha cuenta, mensajes, fotografías, videos y cualquier otro tipo de contenido; y</li>
                <li>envíe al correo electrónico del Usuario vinculado a la Cuenta Personal, información o mensajes con la finalidad descrita en la sección “Uso que hacemos de la Información” abajo.</li>
            </ul>
            <p>Se acuerda expresamente que en cualquier momento el usuario inscrito en ÉLITE JOYERÍA podrá solicitar la baja o cierre de su solicitud de inscripción, y/o el cierre de su cuenta o eliminación de su cuenta e información de la base de datos de ÉLITE JOYERÍA. Por favor revisa la sección “Derechos de acceso, cancelación y rectificación de la información personal” abajo.</p>
            <p>ÉLITE JOYERÍA recoge y almacena automáticamente cierta información sobre la actividad de los usuarios y visitantes dentro de su sitio web. Tal información puede incluir la URL de la que provienen (estén o no en nuestro sitio web), a qué URL acceden seguidamente (estén o no en nuestro sitio web), qué navegador están usando, y sus direcciones IP. También las páginas visitadas, las búsquedas realizadas, las publicaciones, compras o ventas, calificaciones y réplicas ingresadas, mensajes en los foros, entre otra información podrá ser almacenada y retenida.</p>
            <p>En cuanto a los potenciales usuarios, ÉLITE JOYERÍA no almacenará nombres, direcciones postales, datos bancarios, números de cédula de identidad y/o documentos de identidad, ni ninguna otra información que permita identificar o haga identificable a una persona. Solo almacenará números de teléfonos celulares y correos electrónicos.</p>
            <p>Si los usuarios nos envían correspondencia sean correos electrónicos o cartas, o si otros usuarios o terceros nos envían correspondencia sobre las actividades o sobre los mensajes de otros usuarios en nuestro sitio, podemos recoger y almacenar tal Información Personal, incluyendo direcciones de e-mail.</p>
            <p>&nbsp;</p>
            <p><strong>Uso que hacemos de la información</strong></p>
            <p>Para suministrar un excelente servicio y para que los usuarios puedan realizar operaciones en forma ágil y segura, ÉLITE JOYERÍA requiere cierta información de carácter personal, incluyendo dirección de e-mail. La recolección de información nos permite ofrecer a los usuarios servicios y funcionalidades que se adecuen mejor a sus necesidades y personalizar nuestros servicios para hacer que sus experiencias con ÉLITE JOYERÍA sean lo más cómodas posible. La Información Personal que recabamos tiene las siguientes finalidades:</p>
            <p>Ayudar al comprador y vendedor a entrar en contacto directo en la oportunidad que corresponda según la modalidad de la compra. En este caso, ÉLITE JOYERÍA suministrará a los interesados sus datos personales (nombre, teléfonos, localidad y correo electrónico), a través de correo electrónico o a través del sitio. La información así conocida por el comprador o el vendedor, sólo podrá ser utilizada a efectos de concluir la operación originada en ÉLITE JOYERÍA y no deberá ser empleada por ninguno de ellos con fines publicitarios o promocionales u otras actividades no relacionadas con ÉLITE JOYERÍA, salvo la expresa autorización del usuario.</p>
            <p>Desarrollar estudios internos sobre los intereses, comportamientos y demografía de los usuarios para comprender mejor sus necesidades e intereses y ofrecer mejores servicios o proveerles información relacionada.</p>
            <p>Mejorar nuestras iniciativas comerciales y promocionales y analizar las páginas visitadas las búsquedas realizadas por los usuarios, para mejorar nuestra oferta de contenidos y artículos, personalizar dichos contenidos, su presentación y servicios.</p>
            <p>Enviar información o mensajes por e-mail sobre nuevos servicios, mostrar publicidad o promociones, banners, de interés para nuestros usuarios, noticias sobre ÉLITE JOYERÍA, además de la información expresamente autorizada en la sección de preferencias. Si el usuario lo prefiere, puede solicitar que lo excluyan de las listas para el envío de información promocional o publicitaria. Por favor aprende a hacerlo la sección “Cambio de preferencias de e-mail” abajo.</p>
            <p>Enviar información o avisos por mensajes cortos de texto (SMS) al teléfono celular suministrado por el usuario a ÉLITE JOYERÍA. Los mensajes cortos de texto podrán contener avisos publicitarios y/o promocionales de ÉLITE JOYERÍA y/o terceros, así como información sobre los servicios de ÉLITE JOYERÍA, incluyendo en particular, pero sin limitación, recordatorios de vencimientos de pagos y otras obligaciones adquiridas por el uso de los servicios prestados por ÉLITE JOYERÍA.</p>
            <p>Los ganadores de las Promociones y/o concursos realizados por ÉLITE JOYERÍA autorizan expresamente a difundir sus nombres, datos personales e imágenes y los de sus familias, por los medios y en las formas que consideren convenientes, con fines publicitarios y/o promocionales, sin derecho a compensación alguna.</p>
            <p>Compartir la información Personal (incluyendo dirección de e-mail) con los proveedores de servicios o las empresas de “outsourcing” que contribuyan a mejorar o facilitar las operaciones a través de ÉLITE JOYERÍA, como (sin limitarse a) servicios de transporte, medios de pago, seguros o intermediarios en la gestión de pagos, call centers o programas de fidelidad, entre otros. ÉLITE JOYERÍA velará porque se cumplan ciertos estándares, mediante la firma de acuerdos o convenios cuyo objeto sea la privacidad de los datos personales de nuestros usuarios. No obstante, ÉLITE JOYERÍA no se hace responsable por el uso indebido de la Información Personal del usuario que hagan estas compañías o sitios de Internet. En algunos casos, estos proveedores de servicios serán quienes recojan información directamente del usuario (por ejemplo, si les solicitamos que realicen encuestas o estudios). En tales casos, podrá recibir una notificación acerca de la participación de un proveedor de servicios en tales actividades, y quedará a discreción del usuario toda la información que quiera brindarle y los usos adicionales que los proveedores decidan hacer. En caso de que facilites, por propia iniciativa información adicional a dichos prestadores de servicios directamente, tales Prestadores usarán esta información conforme a sus propias políticas de privacidad. Si decidimos revelar o compartir Información Personal con terceros que no son proveedores de servicios o empresas afiliadas o relacionadas con ÉLITE JOYERÍA, requeriremos tu consentimiento.</p>
            <p>Entre los proveedores de servicios que recogen información directamente del usuario se encuentra Google Inc., una compañía de Delaware cuya oficina principal está en 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, Estados Unidos (“Google”). Mediante el uso de “cookies” (ver apartado sobre “Cookies” más adelante), Google obtiene cierta información sobre la actividad de los usuarios de ÉLITE JOYERÍA y sus direcciones IP, que es directamente transmitida y archivada por Google en los servidores de Estados Unidos. Google usará esta información por cuenta de ÉLITE JOYERÍA con el propósito de analizar y confeccionar informes sobre la actividad de los usuarios en Internet, con miras a mejorar los servicios prestados por nuestro sitio web. Google podrá transmitir dicha información a terceros cuando así se lo requiera la normativa aplicable, o cuando dichos terceros procesen la información por cuenta de Google. El usuario consiente expresamente el tratamiento de su información por Google en la forma y para los fines aquí indicados.</p>
            <p>Suministrar la información personal de los usuarios a las entidades que intervengan en la resolución de disputas entre los mismos, tales como: Compañías de Seguros, Amigables Componedores o Tribunales de Arbitraje o tribunales competentes para solucionar tales disputas.</p>
            <p>&nbsp;</p>
            <p><strong>Confidencialidad de la Información</strong></p>
            <p>Una vez inscrito en su sitio Web, ÉLITE JOYERÍA no venderá, alquilará o compartirá la Información Personal excepto en las formas establecidas en estas políticas. Sin perjuicio de ello, el usuario consiente en forma expresa que ÉLITE JOYERÍA transfiera total o parcialmente la Información Personal a cualquiera de las sociedades controladas, controlantes y/o vinculadas con ÉLITE JOYERÍA, a cualquier título y en el momento, forma y condiciones que estime pertinentes. Haremos todo lo que esté a nuestro alcance para proteger la privacidad de la información. Puede suceder que, en virtud de órdenes judiciales, o de regulaciones legales, nos veamos compelidos a revelar información a las autoridades o terceras partes bajo ciertas circunstancias, o bien en casos que terceras partes puedan interceptar o acceder a cierta información o transmisiones de datos en cuyo caso ÉLITE JOYERÍA no responderá por la información que sea revelada.</p>
            <p>Bureaus de crédito: el usuario autoriza a ÉLITE JOYERÍA a compartir su Información Personal con bureaus de crédito o compañías de análisis de riesgo, para usarla con fines estadísticos, de control, de supervisión y/o comerciales, así como para reportar el cumplimiento de las obligaciones derivadas del contrato con ÉLITE JOYERÍA a bancos, asociaciones bancarias y/o financieras del país y a cualquier otra organización que mantenga bases de datos con estos fines. El usuario autoriza a ÉLITE JOYERÍA a consultar la información proporcionada por bureaus de crédito o compañías de análisis de riesgo o cualquier otra organización referida a los aspectos antes mencionada.</p>
            <p>&nbsp;</p>
            <p><strong>Clave Personal</strong></p>
            <p>Para acceder a los servicios reservados únicamente para los usuarios debidamente inscritos los usuarios dispondrán de una clave personal. Con ella podrán comprar y calificar entre otras actividades. Esta clave deben mantenerla bajo absoluta confidencialidad y, en ningún caso, deberán revelarla o compartirla con otras personas.</p>
            <p>El usuario será responsable de todos los actos que tengan lugar mediante el uso de su Seudónimo y Clave, lo que incluye hacerse cargo del pago de las tarifas que eventualmente se devenguen o por los perjuicios que puedan sufrir otros usuarios por tal motivo. Si por cualquier razón un usuario creyera que alguien puede conocer su clave, deberá modificarla ingresando desde el menú de navegación en Mi cuenta y una vez allí hacer clic en Mis Datos.</p>
            <p>&nbsp;</p>
            <p><strong>Menores de Edad</strong></p>
            <p>Nuestros servicios sólo están disponibles para aquellas personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no cumplan con esta condición deberán abstenerse de suministrar información personal para ser incluida en nuestras bases de datos. Sin embargo, pueden hacerlo a través de los padres o tutores.</p>
            <p>&nbsp;</p>
            <p><strong>Cookies</strong></p>
            <p>El usuario y el visitante del sitio Web de ÉLITE JOYERÍA conoce y acepta que ÉLITE JOYERÍA podrá utilizar un sistema de seguimiento mediante la utilización de cookies (las “Cookies”). Las Cookies son pequeños archivos que se instalan en el disco rígido, con una duración limitada en el tiempo que ayudan a personalizar los servicios. También ofrecemos ciertas funcionalidades que sólo están disponibles mediante el empleo de Cookies. Las Cookies se utilizan con el fin de conocer los intereses, el comportamiento y la demografía de quienes visitan o son usuarios de nuestro Sitio Web y de esa forma, comprender mejor sus necesidades e intereses y darles un mejor servicio o proveerle información relacionada. También usaremos la información obtenida por intermedio de las Cookies para analizar las páginas navegadas por el visitante o usuario, las búsquedas realizadas, mejorar nuestras iniciativas comerciales y promocionales, mostrar publicidad o promociones, banners de interés, noticias sobre ÉLITE JOYERÍA, perfeccionar nuestra oferta de contenidos y artículos, personalizar dichos contenidos, presentación y servicios; también podremos utilizar Cookies para promover y hacer cumplir las reglas y seguridad del sitio. ÉLITE JOYERÍA podrá agregar Cookies en los e-mails que envíe para medir la efectividad de las promociones.</p>
            <p>Utilizamos adicionalmente las Cookies para que el usuario no tenga que introducir su clave tan frecuentemente durante una sesión de navegación, también para contabilizar y corroborar las inscripciones, la actividad del usuario y otros conceptos para acuerdos comerciales, siempre teniendo como objetivo de la instalación de las Cookies, el beneficio del usuario que la recibe, y no será usado con otros fines ajenos a ÉLITE JOYERÍA.</p>
            <p>Se establece que la instalación, permanencia y existencia de las Cookies en el computador del usuario depende de su exclusiva voluntad y puede ser eliminada de su computador cuando el usuario así lo desee. Para saber cómo quitar las Cookies del sistema es necesario revisar la sección Ayuda (Help) del navegador.</p>
            <p>Adicionalmente, se pueden encontrar Cookies u otros sistemas similares instalados por terceros en ciertas páginas de nuestro sitio Web. Por ejemplo, al navegar por una página creada por un usuario, puede que exista una Cookie emplazada en tal página.</p>
            <p>Se aclara expresamente que estas políticas cubren la utilización de Cookies por este sitio y no la utilización de Cookies por parte de anunciantes. Nosotros no controlamos el uso de Cookies por terceros.</p>
            <p>&nbsp;</p>
            <p><strong>Web Beacons</strong></p>
            <p>Un Web beacon es una imagen electrónica, también llamada single-pixel (1 x 1) o pixel transparente, que es colocada en código de una página Web. Un Web beacon tiene finalidades similares a las Cookies. Adicionalmente un Web beacon es utilizado para medir patrones de tráfico de los usuarios de una página a otra con el objeto de maximizar como fluye el tráfico a través de la Web. El usuario y el visitante del sitio Web de ÉLITE JOYERÍA conoce y acepta que podrá utilizar un sistema de seguimiento mediante la utilización de Web beacons.</p>
            <p>&nbsp;</p>
            <p><strong>Spam</strong></p>
            <p>ÉLITE JOYERÍA y sus usuarios no aceptan conductas consideradas “spamming”, ya sea en opiniones, preguntas, respuestas y/o el envío no solicitado de correos electrónicos. Queda absolutamente prohibido el envío indiscriminado de mensajes de cualquier naturaleza entre los usuarios de ÉLITE JOYERÍA.</p>
            <p>ÉLITE JOYERÍA podrá suspender o inhabilitar definitivamente a aquellos usuarios que violen esta política.</p>
            <p>&nbsp;</p>
            <p><strong>Orden de autoridades competentes – Requerimientos Legales</strong></p>
            <p>ÉLITE JOYERÍA coopera con las autoridades competentes y con otros terceros para garantizar el cumplimiento de las leyes, por ejemplo, en materia de protección de derechos de propiedad industrial e intelectual, prevención del fraude y otras materias.</p>
            <p>ÉLITE JOYERÍA podrá revelar la Información Personal de sus usuarios bajo requerimiento de la autoridades judiciales o gubernamentales competentes para efectos de investigaciones conducidas por ellas, aunque no exista una orden ni una citación ejecutiva o judicial, o por ejemplo (y sin limitación a este supuesto) cuando se trate de investigaciones de carácter penal o de fraude o las relacionadas con piratería informática o la violación de derechos de autor. En tales situaciones, ÉLITE JOYERÍA colaborará con las autoridades competentes con el fin de salvaguardar la integridad y la seguridad de la Comunidad y la de sus usuarios.</p>
            <p>ÉLITE JOYERÍA puede (y los usuarios lo autorizan expresamente) comunicar cualquier Información Personal sobre sus usuarios con la finalidad de cumplir la normativa aplicable y cooperar con las autoridades competentes en la medida en que discrecionalmente lo entendamos necesario y adecuado en relación con cualquier investigación de un ilícito o un fraude, infracción de derechos de propiedad industrial o intelectual, u otra actividad que sea ilegal o que pueda exponer a ÉLITE JOYERÍA o a sus usuarios a cualquier responsabilidad legal. Además, podemos (y los usuarios lo autorizan expresamente) comunicar su nombre completo, seudónimo, domicilio, ciudad, región, código postal, país, número de teléfono, dirección de correo electrónico, etc. a los participantes en el Programa de Protección de Propiedad Intelectual de ÉLITE JOYERÍA en la forma que, a nuestra discreción, entendamos necesaria o adecuada en relación con la investigación del fraude, infracción de derechos de propiedad industrial o intelectual, piratería, o cualquier otra actividad ilegal. Este derecho será ejercido por ÉLITE JOYERÍA a efectos de cooperar con el cumplimiento y ejecución de la ley, independientemente que no exista una orden judicial o administrativa al efecto.</p>
            <p>Además, ÉLITE JOYERÍA se reserva el derecho (y nos autorizas expresamente a ello) de comunicar información sobre sus usuarios a otros usuarios, entidades o terceros cuando haya motivos suficientes para considerar que la actividad de un usuario sea sospechosa de intentar o cometer un delito o intentar perjudicar a otras personas. Este derecho será utilizado por ÉLITE JOYERÍA a su entera discreción cuando lo considere apropiado o necesario para mantener la integridad y la seguridad de la Comunidad y la de sus usuarios, para hacer cumplir los Términos y Condiciones 1 Generales y demás Políticas del sitio y a efectos de cooperar con la ejecución y cumplimiento de la ley. Este derecho será ejercido por ÉLITE JOYERÍA independientemente que no exista una orden judicial o administrativa al efecto.</p>
            <p>&nbsp;</p>
            <p><strong>Seguridad. Almacenamiento de la información</strong></p>
            <p>ÉLITE JOYERÍA está obligado a cumplir con toda la normativa aplicable en materia de medidas de seguridad aplicables a la Información Personal. Adicionalmente, ÉLITE JOYERÍA usa los estándares de la industria entre materia de protección de la confidencialidad de su Información Personal, incluyendo, en otras medidas, cortafuegos (“firewalls”) y Secure Socket Layers (“SSL”). ÉLITE JOYERÍA considera a los datos de sus usuarios como un activo que debe ser protegido de cualquier pérdida o acceso no autorizado. Empleamos diversas técnicas de seguridad para proteger tales datos de accesos no autorizados por usuarios de dentro o fuera de nuestra compañía. Sin embargo, es necesario tener muy en cuenta que la seguridad perfecta no existe en Internet.</p>
            <p>Por ello, ÉLITE JOYERÍA no se hace responsable por interceptaciones ilegales o violación de sus sistemas o bases de datos por parte de personas no autorizadas. ÉLITE JOYERÍA, tampoco se hace responsable por la indebida utilización de la información obtenida por esos medios.</p>
            <p>Todos los datos personales de los usuarios serán almacenados en un fichero automatizado de datos personales. El fichero de Datos Personales de los usuarios de ÉLITE JOYERÍA reside en EE.UU. El usuario al inscribirse en ÉLITE JOYERÍA confirma que está informado de la residencia de este fichero y autoriza esta transferencia internacional de sus datos.</p>
            <p>&nbsp;</p>
            <p><strong>Cambio en las preferencias de e-mails</strong></p>
            <p>Sin perjuicio que ÉLITE JOYERÍA quiere mantener a sus usuarios actualizados en todo momento sobre promociones, novedades, cambios, etc. los usuarios pueden seleccionar los e-mails e información promocional que gustarían recibir de ÉLITE JOYERÍA.</p>
            <p>Si no quieres recibir correos electrónicos, puedes desuscribirte, cambiando tus preferencias de e-mail siguiendo las instrucciones que proporcionamos en nuestras comunicaciones o bien accediendo a tu cuenta en la sección M. En esa sección podrás seleccionar las preferencias para que sean tenidas en cuenta por ÉLITE JOYERÍA en las futuras comunicaciones o enviando tus preferencias por correo a la dirección postal indicada en estas políticas.</p>
            <p>&nbsp;</p>
            <p><strong>Responsable de Protección de Datos</strong></p>
            <p>Nuestro Responsable de Protección de Datos es la Sra. Carolina Garcés, a quien podrás contactar a través de los medios detallados más abajo.</p>
            <p>Área encargada de peticiones, consultas y reclamos de datos personales</p>
            <p>El área encargada de atender las peticiones, consultas y reclamos de los titulares para ejercer sus derechos a conocer, actualizar, rectificar y suprimir sus datos y revocar su autorización es el Área de Atención al Cliente.</p>
            <p><strong>Medios para ejercer los derechos de acceso, retiro y rectificación de los datos personales</strong></p>
            <p>Para hacer cualquier consulta, reclamo y/o petición relativa a tus datos personales, podrás hacerlo ingresando en la sección Mi cuenta y haciendo clic en Mis Datos, contactándonos a través de este formulario, o bien por correo postal a la Calle 52 # 47-28, Edificio La Ceiba, local 425, Medellín, Antioquia – Colombia</p>
            <p>ÉLITE JOYERÍA responderá a la solicitud en el plazo estipulado por la Ley 1581 de 2012. Cuando no fuere posible atender tu consulta dentro de dicho término, te avisaremos oportunamente, expresando los motivos de la demora y señalando la fecha en que será atendida.</p>
            <p>Ten en cuenta que la solicitud de retiro o supresión no procederá cuando exista el deber contractual o legal de mantenerlo en nuestra base de datos, como ocurre, por ejemplo, con las calificaciones que dan otros usuarios.</p>
            <p>Período de vigencia de los datos Los datos personales de los usuarios permanecerán en nuestra base de datos durante el plazo necesario para cumplir los usos y finalidades descritos en las Políticas de Privacidad o en los Términos y Condiciones.</p>
            <p>&nbsp;</p>
        </div>
    </div>
</div>